### ISSUE TITLE
No debug capabilities

### ISSUE THREAD

**Issue by jtlutgen** [spoonboy-io/switch#1]
There needs to be a debug flag for switch to allow me to see the json payload that is being returned - which may require me to edit specific fields for the root, name, value fields.

**Comment by olliephillips** [comment]
Thanks, yes, I can see how getting more feedback on any problems is better than hitting a brick wall with it. Will look at this. Thanks for the feedback.

**Comment by olliephillips** [comment]
Added in [v0.0.4](https://github.com/spoonboy-io/switch/releases/tag/v0.0.4)
